### ISSUE TITLE
i can't leave a group

### ISSUE THREAD

**Issue by Abdallahyasser14** [PS-Track/PSTrack#122]
I think we should add a feature that allows users to leave a group. Right now, I can't join another group because I'm already in one. I tried to join Group 6, but I'm currently a member of another group and there is no option to leave it.

**Comment by husamql3** [comment]
@Abdallahyasser14 

Thanks for your comment. May you send me your email so I will move you to group 6?
Unfortunately, it's not an implemented feature; I'm working on it rn.

**Comment by Abdallahyasser14** [comment]
abdallahshady4@gmail.com

**Comment by husamql3** [comment]
done

**Comment by Abdallahyasser14** [comment]
Thank you 
I still have this screen is that normal? 

![Image](https://github.com/user-attachments/assets/49fb895f-6dd7-42dc-a79f-237222221b68)

**Comment by husamql3** [comment]
Yes, Group 6 did not start yet. It will send you a email when it start
